import 'package:flutter/material.dart';

class AppLocalizations {
  static const Map<String, Locale> supportedLanguages = {
    'English': Locale('en', 'US'),
    'Hindi': Locale('hi', 'IN'),
    'Tamil': Locale('ta', 'IN'),
    'Telugu': Locale('te', 'IN'),
    'Bengali': Locale('bn', 'IN'),
    'Spanish': Locale('es', 'ES'),
    'French': Locale('fr', 'FR'),
  };

  static const List<Locale> supportedLocales = [
    Locale('en', 'US'), // English
    Locale('hi', 'IN'), // Hindi
    Locale('ta', 'IN'), // Tamil
    Locale('te', 'IN'), // Telugu
    Locale('bn', 'IN'), // Bengali
    Locale('es', 'ES'), // Spanish
    Locale('fr', 'FR'), // French
  ];

  static Locale getLocaleFromLanguageName(String languageName) {
    return supportedLanguages[languageName] ?? const Locale('en', 'US');
  }

  static String getLanguageNameFromLocale(Locale locale) {
    return supportedLanguages.entries
        .firstWhere(
          (entry) => entry.value == locale,
          orElse: () => const MapEntry('English', Locale('en', 'US')),
        )
        .key;
  }

  // Basic translations for common UI elements
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'currently': 'Currently',
      'sound_effects': 'Sound Effects',
      'vibration': 'Vibration',
      'theme_changed': 'Theme changed successfully',
      'language_changed': 'Language changed to',
      'select_language': 'Select Language',
      'cancel': 'Cancel',
      'notifications': 'Notifications',
      'account': 'Account',
      'home': 'Home',
      'profile': 'Profile',
      'logout': 'Logout',
      'privacy_security': 'Privacy & Security',
      'payment_methods': 'Payment Methods',
      'push_notifications': 'Push Notifications',
      'email_notifications': 'Email Notifications',
      'study_reminders': 'Study Reminders',
      'session_reminders': 'Session Reminders',
      'notification_settings': 'Notification Settings',
      'app_preferences': 'App Preferences',
      'data_storage': 'Data & Storage',
      'learning': 'Learning',
      'teaching': 'Teaching',
      'support': 'Support & Legal',
      'password_privacy_settings': 'Password, privacy settings',
      'manage_cards_billing': 'Manage cards and billing',
      'receive_notifications_device': 'Receive notifications on your device',
      'get_updates_email': 'Get updates via email',
      'daily_study_reminders': 'Daily study session reminders',
      'upcoming_session_notifications': 'Upcoming session notifications',
      'customize_notification_preferences':
          'Customize notification preferences',
      'use_dark_theme': 'Use dark theme',
      'play_sounds_actions': 'Play sounds for app actions',
      'vibrate_notifications': 'Vibrate for notifications',
      'auto_sync': 'Auto Sync',
      'automatically_sync_data': 'Automatically sync data',
      'data_usage': 'Data Usage',
      'download_content': 'Download content',
      'clear_cache': 'Clear Cache',
      'free_storage_space': 'Free up storage space',
      'offline_content': 'Offline Content',
      'manage_downloaded_materials': 'Manage downloaded materials',
      'session_preferences': 'Session Preferences',
      'default_session_duration': 'Default session duration, breaks',
      'learning_goals': 'Learning Goals',
      'set_study_targets': 'Set your study targets',
      'performance_tracking': 'Performance Tracking',
      'track_progress': 'How we track your progress',
      'availability_settings': 'Availability Settings',
      'set_teaching_hours': 'Set your teaching hours',
      'rate_preferences': 'Rate Preferences',
      'hourly_rates_subjects': 'Set hourly rates by subject',
      'student_management': 'Student Management',
      'manage_student_interactions': 'Manage student interactions',
      'help_center': 'Help Center',
      'faq_tutorials': 'FAQ and tutorials',
      'contact_support': 'Contact Support',
      'get_help_issues': 'Get help with issues',
      'terms_conditions': 'Terms & Conditions',
      'privacy_policy': 'Privacy Policy',
      'about_app': 'About App',
      'version_info': 'Version and app information',
      'check_updates': 'Check Updates',
      'rate_app': 'Rate App',
      'help_us_improve': 'Help us improve',
      'report_issue': 'Report Issue',
      'found_bug': 'Found a bug? Let us know',
      'book_session': 'Book Session',
      'chat': 'Chat',
      'progress': 'Progress',
      'wallet': 'Wallet',
      'dashboard': 'Dashboard',
      'requests': 'Requests',
      'earnings': 'Earnings',
      'availability': 'Availability',
      'student_menu': 'Student Menu',
      'mentor_menu': 'Mentor Menu',
      'help_support': 'Help & Support',
      'websocket_demo': 'WebSocket Demo',
      'realtime_features_demo': 'Real-time features demo',
    },
    'hi': {
      'settings': 'सेटिंग्स',
      'dark_mode': 'डार्क मोड',
      'language': 'भाषा',
      'currently': 'वर्तमान में',
      'sound_effects': 'ध्वनि प्रभाव',
      'vibration': 'कंपन',
      'theme_changed': 'थीम सफलतापूर्वक बदल गई',
      'language_changed': 'भाषा बदलकर',
      'select_language': 'भाषा चुनें',
      'cancel': 'रद्द करें',
      'notifications': 'सूचनाएं',
      'account': 'खाता',
      'home': 'होम',
      'profile': 'प्रोफाइल',
      'logout': 'लॉग आउट',
      'privacy_security': 'गोपनीयता और सुरक्षा',
      'payment_methods': 'भुगतान के तरीके',
      'push_notifications': 'पुश नोटिफिकेशन',
      'email_notifications': 'ईमेल नोटिफिकेशन',
      'study_reminders': 'अध्ययन रिमाइंडर',
      'session_reminders': 'सत्र रिमाइंडर',
      'notification_settings': 'नोटिफिकेशन सेटिंग्स',
      'app_preferences': 'ऐप प्राथमिकताएं',
      'data_storage': 'डेटा और भंडारण',
      'learning': 'शिक्षा',
      'teaching': 'शिक्षण',
      'support': 'सहायता और कानूनी',
      'password_privacy_settings': 'पासवर्ड, गोपनीयता सेटिंग्स',
      'manage_cards_billing': 'कार्ड और बिलिंग प्रबंधित करें',
      'receive_notifications_device': 'अपने डिवाइस पर नोटिफिकेशन प्राप्त करें',
      'get_updates_email': 'ईमेल के माध्यम से अपडेट प्राप्त करें',
      'daily_study_reminders': 'दैनिक अध्ययन सत्र रिमाइंडर',
      'upcoming_session_notifications': 'आगामी सत्र नोटिफिकेशन',
      'customize_notification_preferences':
          'नोटिफिकेशन प्राथमिकताओं को अनुकूलित करें',
      'use_dark_theme': 'डार्क थीम का उपयोग करें',
      'play_sounds_actions': 'ऐप क्रियाओं के लिए ध्वनि बजाएं',
      'vibrate_notifications': 'नोटिफिकेशन के लिए कंपन करें',
      'auto_sync': 'ऑटो सिंक',
      'automatically_sync_data': 'डेटा को स्वचालित रूप से सिंक करें',
      'data_usage': 'डेटा उपयोग',
      'download_content': 'सामग्री डाउनलोड करें',
      'clear_cache': 'कैश साफ़ करें',
      'free_storage_space': 'भंडारण स्थान खाली करें',
      'offline_content': 'ऑफ़लाइन सामग्री',
      'manage_downloaded_materials': 'डाउनलोड की गई सामग्री प्रबंधित करें',
      'session_preferences': 'सत्र प्राथमिकताएं',
      'default_session_duration': 'डिफ़ॉल्ट सत्र अवधि, विराम',
      'learning_goals': 'शिक्षा लक्ष्य',
      'set_study_targets': 'अपने अध्ययन लक्ष्य निर्धारित करें',
      'performance_tracking': 'प्रदर्शन ट्रैकिंग',
      'track_progress': 'हम आपकी प्रगति को कैसे ट्रैक करते हैं',
      'availability_settings': 'उपलब्धता सेटिंग्स',
      'set_teaching_hours': 'अपने शिक्षण घंटे निर्धारित करें',
      'rate_preferences': 'दर प्राथमिकताएं',
      'hourly_rates_subjects': 'विषय के अनुसार घंटे की दरें निर्धारित करें',
      'student_management': 'छात्र प्रबंधन',
      'manage_student_interactions': 'छात्र इंटरैक्शन प्रबंधित करें',
      'help_center': 'सहायता केंद्र',
      'faq_tutorials': 'FAQ और ट्यूटोरियल',
      'contact_support': 'सहायता से संपर्क करें',
      'get_help_issues': 'समस्याओं के साथ सहायता प्राप्त करें',
      'terms_conditions': 'नियम और शर्तें',
      'privacy_policy': 'गोपनीयता नीति',
      'about_app': 'ऐप के बारे में',
      'version_info': 'संस्करण और ऐप जानकारी',
      'check_updates': 'अपडेट जांचें',
      'rate_app': 'ऐप को रेट करें',
      'help_us_improve': 'हमें बेहतर बनाने में मदद करें',
      'report_issue': 'समस्या की रिपोर्ट करें',
      'found_bug': 'कोई बग मिला? हमें बताएं',
      'book_session': 'सत्र बुक करें',
      'chat': 'चैट',
      'progress': 'प्रगति',
      'wallet': 'वॉलेट',
      'dashboard': 'डैशबोर्ड',
      'requests': 'अनुरोध',
      'earnings': 'कमाई',
      'availability': 'उपलब्धता',
      'student_menu': 'छात्र मेनू',
      'mentor_menu': 'गुरु मेनू',
      'help_support': 'सहायता और समर्थन',
      'websocket_demo': 'वेबसॉकेट डेमो',
      'realtime_features_demo': 'रियल-टाइम फीचर्स डेमो',
    },
    'ta': {
      'settings': 'அமைப்புகள்',
      'dark_mode': 'இருண்ட பயன்முறை',
      'language': 'மொழி',
      'currently': 'தற்போது',
      'sound_effects': 'ஒலி விளைவுகள்',
      'vibration': 'அதிர்வு',
      'theme_changed': 'தீம் வெற்றிகரமாக மாற்றப்பட்டது',
      'language_changed': 'மொழி மாற்றப்பட்டது',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'cancel': 'ரத்து செய்',
      'notifications': 'அறிவிப்புகள்',
      'account': 'கணக்கு',
      'home': 'முகப்பு',
      'profile': 'சுயவிவரம்',
      'logout': 'வெளியேறு',
      'privacy_security': 'தனியுரிமை மற்றும் பாதுகாப்பு',
      'payment_methods': 'பணம் செலுத்தும் முறைகள்',
      'push_notifications': 'புஷ் அறிவிப்புகள்',
      'email_notifications': 'மின்னஞ்சல் அறிவிப்புகள்',
      'study_reminders': 'படிப்பு நினைவூட்டல்கள்',
      'session_reminders': 'அமர்வு நினைவூட்டல்கள்',
      'notification_settings': 'அறிவிப்பு அமைப்புகள்',
      'app_preferences': 'ஆப் விருப்பத்தேர்வுகள்',
      'data_storage': 'தரவு மற்றும் சேமிப்பு',
      'learning': 'கற்றல்',
      'teaching': 'கற்பித்தல்',
      'support': 'ஆதரவு மற்றும் சட்டம்',
      'password_privacy_settings': 'கடவுச்சொல், தனியுரிமை அமைப்புகள்',
      'manage_cards_billing': 'கார்டுகள் மற்றும் கட்டணத்தை நிர்வகிக்கவும்',
      'receive_notifications_device':
          'உங்கள் சாधனத்தில் அறிவிப்புகளைப் பெறுங்கள்',
      'get_updates_email': 'மின்னஞ்சல் வழியாக புதுப்பிப்புகளைப் பெறுங்கள்',
      'daily_study_reminders': 'தினசரி படிப்பு அமர்வு நினைவூட்டல்கள்',
      'upcoming_session_notifications': 'வரவிருக்கும் அமர்வு அறிவிப்புகள்',
      'customize_notification_preferences':
          'அறிவிப்பு விருப்பத்தேர்வுகளை தனிப்பயனாக்கவும்',
      'use_dark_theme': 'இருண்ட தீம் பயன்படுத்தவும்',
      'play_sounds_actions': 'ஆப் செயல்களுக்கு ஒலிகளை இயக்கவும்',
      'vibrate_notifications': 'அறிவிப்புகளுக்கு அதிர்வு',
      'auto_sync': 'தானியங்கி ஒத்திசைவு',
      'automatically_sync_data': 'தானியங்கியாக தரவை ஒத்திசைக்கவும்',
      'data_usage': 'தரவு பயன்பாடு',
      'download_content': 'உள்ளடக்கத்தை பதிவிறக்கவும்',
      'clear_cache': 'கேச் அழிக்கவும்',
      'free_storage_space': 'சேமிப்பு இடத்தை விடுவிக்கவும்',
      'offline_content': 'ஆஃப்லைன் உள்ளடக்கம்',
      'manage_downloaded_materials':
          'பதிவிறக்கம் செய்யப்பட்ட பொருட்களை நிர்வகிக்கவும்',
      'session_preferences': 'அமர்வு விருப்பத்தேர்வுகள்',
      'default_session_duration': 'இயல்புநிலை அமர்வு காலம், இடைவெளிகள்',
      'learning_goals': 'கற்றல் இலக்குகள்',
      'set_study_targets': 'உங்கள் படிப்பு இலக்குகளை அமைக்கவும்',
      'performance_tracking': 'செயல்திறன் கண்காணிப்பு',
      'track_progress': 'உங்கள் முன்னேற்றத்தை எவ்வாறு கண்காணிக்கிறோம்',
      'availability_settings': 'கிடைக்கும் அமைப்புகள்',
      'set_teaching_hours': 'உங்கள் கற்பித்தல் நேரத்தை அமைக்கவும்',
      'rate_preferences': 'விகித விருப்பத்தேர்வுகள்',
      'hourly_rates_subjects':
          'பாடத்தின் அடிப்படையில் மணிநேர விகிதங்களை அமைக்கவும்',
      'student_management': 'மாணவர் நிர்வாகம்',
      'manage_student_interactions': 'மாணவர் தொடர்புகளை நிர்வகிக்கவும்',
      'help_center': 'உதவி மையம்',
      'faq_tutorials': 'FAQ மற்றும் பயிற்சிகள்',
      'contact_support': 'ஆதரவைத் தொடர்பு கொள்ளவும்',
      'get_help_issues': 'சிக்கல்களுக்கான உதவி பெறவும்',
      'terms_conditions': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      'privacy_policy': 'தனியுரிமைக் கொள்கை',
      'about_app': 'ஆப் பற்றி',
      'version_info': 'பதிப்பு மற்றும் ஆப் தகவல்',
      'check_updates': 'புதுப்பிப்புகளைச் சரிபார்க்கவும்',
      'rate_app': 'ஆப்பை மதிப்பிடுங்கள்',
      'help_us_improve': 'எங்களை மேம்படுத்த உதவுங்கள்',
      'report_issue': 'சிக்கல் புகார் செய்யவும்',
      'found_bug': 'பிழை கண்டுபிடித்தீர்களா? எங்களுக்குத் தெரியப்படுத்துங்கள்',
      'book_session': 'அமர்வு புக் செய்யுங்கள்',
      'chat': 'அரட்டை',
      'progress': 'முன்னேற்றம்',
      'wallet': 'பணப்பை',
      'dashboard': 'டாஷ்போர்டு',
      'requests': 'கோரிக்கைகள்',
      'earnings': 'வருமானம்',
      'availability': 'கிடைக்கும் நிலை',
      'student_menu': 'மாணவர் மெனு',
      'mentor_menu': 'வழிகாட்டி மெனு',
      'help_support': 'உதவி மற்றும் ஆதரவு',
      'websocket_demo': 'வெப்சாக்கெட் டெமோ',
      'realtime_features_demo': 'நிகழ்நேர அம்சங்கள் டெமோ',
    },
    'te': {
      'settings': 'సెట్టింగులు',
      'dark_mode': 'డార్క్ మోడ్',
      'language': 'భాష',
      'currently': 'ప్రస్తుతం',
      'sound_effects': 'సౌండ్ ఎఫెక్ట్స్',
      'vibration': 'వైబ్రేషన్',
      'theme_changed': 'థీమ్ విజయవంతంగా మార్చబడింది',
      'language_changed': 'భాష మార్చబడింది',
      'select_language': 'భాషను ఎంచుకోండి',
      'cancel': 'రద్దు చేయండి',
      'notifications': 'నోటిఫికేషన్లు',
      'account': 'ఖాతా',
      'home': 'హోమ్',
      'profile': 'ప్రొఫైల్',
      'logout': 'లాగ్ అవుట్',
      'privacy_security': 'గోప్యత & భద్రత',
      'payment_methods': 'చెల్లింపు పద్ధతులు',
      'push_notifications': 'పుష్ నోటిఫికేషన్లు',
      'email_notifications': 'ఇమెయిల్ నోటిఫికేషన్లు',
      'study_reminders': 'అధ్యయన రిమైండర్లు',
      'session_reminders': 'సెషన్ రిమైండర్లు',
      'notification_settings': 'నోటిఫికేషన్ సెట్టింగులు',
      'app_preferences': 'యాప్ ప్రాధాన్యతలు',
      'data_storage': 'డేటా & స్టోరేజ్',
      'learning': 'అభ్యాసం',
      'teaching': 'బోధన',
      'support': 'మద్దతు & చట్టపరమైన',
      'password_privacy_settings': 'పాస్‌వర్డ్, గోప్యతా సెట్టింగులు',
      'manage_cards_billing': 'కార్డులు మరియు బిల్లింగ్ నిర్వహించండి',
      'receive_notifications_device': 'మీ పరికరంలో నోటిఫికేషన్లను స్వీకరించండి',
      'get_updates_email': 'ఇమెయిల్ ద్వారా అప్‌డేట్లు పొందండి',
      'daily_study_reminders': 'రోజువారీ అధ్యయన సెషన్ రిమైండర్లు',
      'upcoming_session_notifications': 'రాబోయే సెషన్ నోటిఫికేషన్లు',
      'customize_notification_preferences':
          'నోటిఫికేషన్ ప్రాధాన్యతలను అనుకూలీకరించండి',
      'use_dark_theme': 'డార్క్ థీమ్ ఉపయోగించండి',
      'play_sounds_actions': 'యాప్ చర్యలకు శబ్దాలను ప్లే చేయండి',
      'vibrate_notifications': 'నోటిఫికేషన్లకు వైబ్రేట్ చేయండి',
      'auto_sync': 'ఆటో సింక్',
      'automatically_sync_data': 'డేటాను స్వయంచాలకంగా సింక్ చేయండి',
      'data_usage': 'డేటా వినియోగం',
      'download_content': 'కంటెంట్ డౌన్‌లోడ్ చేయండి',
      'clear_cache': 'కాష్ క్లియర్ చేయండి',
      'free_storage_space': 'స్టోరేజ్ స్థలాన్ని ఖాళీ చేయండి',
      'offline_content': 'ఆఫ్‌లైన్ కంటెంట్',
      'manage_downloaded_materials': 'డౌన్‌లోడ్ చేసిన మెటీరియల్స్ నిర్వహించండి',
      'session_preferences': 'సెషన్ ప్రాధాన్యతలు',
      'default_session_duration': 'డిఫాల్ట్ సెషన్ వ్యవధి, విరామాలు',
      'learning_goals': 'అభ్యాస లక్ష్యాలు',
      'set_study_targets': 'మీ అధ్యయన లక్ష్యాలను సెట్ చేయండి',
      'performance_tracking': 'పనితీరు ట్రాకింగ్',
      'track_progress': 'మేము మీ పురోగతిని ఎలా ట్రాక్ చేస్తాము',
      'availability_settings': 'లభ్యతా సెట్టింగులు',
      'set_teaching_hours': 'మీ బోధనా గంటలను సెట్ చేయండి',
      'rate_preferences': 'రేట్ ప్రాధాన్యతలు',
      'hourly_rates_subjects': 'విషయాల ప్రకారం గంట రేట్లు సెట్ చేయండి',
      'student_management': 'విద్యార్థి నిర్వహణ',
      'manage_student_interactions': 'విద్యార్థి ఇంటరాక్షన్లను నిర్వహించండి',
      'help_center': 'సహాయ కేంద్రం',
      'faq_tutorials': 'FAQ మరియు ట్యుటోరియల్స్',
      'contact_support': 'మద్దతును సంప్రదించండి',
      'get_help_issues': 'సమస్యలతో సహాయం పొందండి',
      'terms_conditions': 'నిబంధనలు & షరతులు',
      'privacy_policy': 'గోప్యతా విధానం',
      'about_app': 'యాప్ గురించి',
      'version_info': 'వెర్షన్ మరియు యాప్ సమాచారం',
      'check_updates': 'అప్‌డేట్లను తనిఖీ చేయండి',
      'rate_app': 'యాప్‌ను రేట్ చేయండి',
      'help_us_improve': 'మాను మెరుగుపరచడంలో సహాయపడండి',
      'report_issue': 'సమస్యను నివేదించండి',
      'found_bug': 'బగ్ దొరికిందా? మాకు తెలియజేయండి',
      'book_session': 'సెషన్ బుక్ చేయండి',
      'chat': 'చాట్',
      'progress': 'పురోగతి',
      'wallet': 'వాలెట్',
      'dashboard': 'డాష్‌బోర్డ్',
      'requests': 'అభ్యర్థనలు',
      'earnings': 'ఆదాయాలు',
      'availability': 'లభ్యత',
      'student_menu': 'విద్యార్థి మెనూ',
      'mentor_menu': 'మెంటర్ మెనూ',
      'help_support': 'సహాయం మరియు మద్దతు',
      'websocket_demo': 'వెబ్‌సాకెట్ డెమో',
      'realtime_features_demo': 'రియల్ టైమ్ ఫీచర్స్ డెమో',
    },
    'bn': {
      'settings': 'সেটিংস',
      'dark_mode': 'ডার্ক মোড',
      'language': 'ভাষা',
      'currently': 'বর্তমানে',
      'sound_effects': 'সাউন্ড এফেক্ট',
      'vibration': 'কম্পন',
      'theme_changed': 'থিম সফলভাবে পরিবর্তিত হয়েছে',
      'language_changed': 'ভাষা পরিবর্তিত হয়েছে',
      'select_language': 'ভাষা নির্বাচন করুন',
      'cancel': 'বাতিল',
      'notifications': 'বিজ্ঞপ্তি',
      'account': 'অ্যাকাউন্ট',
      'home': 'হোম',
      'profile': 'প্রোফাইল',
      'logout': 'লগ আউট',
      'privacy_security': 'গোপনীয়তা ও নিরাপত্তা',
      'payment_methods': 'পেমেন্ট পদ্ধতি',
      'push_notifications': 'পুশ নোটিফিকেশন',
      'email_notifications': 'ইমেইল নোটিফিকেশন',
      'study_reminders': 'অধ্যয়ন অনুস্মারক',
      'session_reminders': 'সেশন অনুস্মারক',
      'notification_settings': 'নোটিফিকেশন সেটিংস',
      'app_preferences': 'অ্যাপ পছন্দসমূহ',
      'data_storage': 'ডেটা ও স্টোরেজ',
      'learning': 'শিক্ষা',
      'teaching': 'শিক্ষণ',
      'support': 'সহায়তা ও আইনি',
      'password_privacy_settings': 'পাসওয়ার্ড, গোপনীয়তা সেটিংস',
      'manage_cards_billing': 'কার্ড এবং বিলিং পরিচালনা করুন',
      'receive_notifications_device': 'আপনার ডিভাইসে নোটিফিকেশন পান',
      'get_updates_email': 'ইমেইলের মাধ্যমে আপডেট পান',
      'daily_study_reminders': 'দৈনিক অধ্যয়ন সেশন অনুস্মারক',
      'upcoming_session_notifications': 'আসন্ন সেশন নোটিফিকেশন',
      'customize_notification_preferences': 'নোটিফিকেশন পছন্দ কাস্টমাইজ করুন',
      'use_dark_theme': 'ডার্ক থিম ব্যবহার করুন',
      'play_sounds_actions': 'অ্যাপ ক্রিয়াগুলির জন্য শব্দ বাজান',
      'vibrate_notifications': 'নোটিফিকেশনের জন্য কম্পন করুন',
      'auto_sync': 'অটো সিঙ্ক',
      'automatically_sync_data': 'স্বয়ংক্রিয়ভাবে ডেটা সিঙ্ক করুন',
      'data_usage': 'ডেটা ব্যবহার',
      'download_content': 'কন্টেন্ট ডাউনলোড করুন',
      'clear_cache': 'ক্যাশ পরিষ্কার করুন',
      'free_storage_space': 'স্টোরেজ স্থান খালি করুন',
      'offline_content': 'অফলাইন কন্টেন্ট',
      'manage_downloaded_materials': 'ডাউনলোড করা উপকরণ পরিচালনা করুন',
      'session_preferences': 'সেশন পছন্দ',
      'default_session_duration': 'ডিফল্ট সেশনের সময়কাল, বিরতি',
      'learning_goals': 'শিক্ষার লক্ষ্য',
      'set_study_targets': 'আপনার অধ্যয়নের লক্ষ্য নির্ধারণ করুন',
      'performance_tracking': 'কর্মক্ষমতা ট্র্যাকিং',
      'track_progress': 'আমরা কীভাবে আপনার অগ্রগতি ট্র্যাক করি',
      'availability_settings': 'উপলব্ধতা সেটিংস',
      'set_teaching_hours': 'আপনার শিক্ষণ ঘন্টা নির্ধারণ করুন',
      'rate_preferences': 'রেট পছন্দ',
      'hourly_rates_subjects': 'বিষয় অনুযায়ী ঘণ্টার হার নির্ধারণ করুন',
      'student_management': 'ছাত্র ব্যবস্থাপনা',
      'manage_student_interactions': 'ছাত্র মিথস্ক্রিয়া পরিচালনা করুন',
      'help_center': 'সহায়তা কেন্দ্র',
      'faq_tutorials': 'FAQ এবং টিউটোরিয়াল',
      'contact_support': 'সহায়তার সাথে যোগাযোগ করুন',
      'get_help_issues': 'সমস্যার সাহায্য পান',
      'terms_conditions': 'নিয়ম ও শর্তাবলী',
      'privacy_policy': 'গোপনীয়তা নীতি',
      'about_app': 'অ্যাপ সম্পর্কে',
      'version_info': 'সংস্করণ এবং অ্যাপ তথ্য',
      'check_updates': 'আপডেট চেক করুন',
      'rate_app': 'অ্যাপ রেট করুন',
      'help_us_improve': 'আমাদের উন্নতিতে সাহায্য করুন',
      'report_issue': 'সমস্যা রিপোর্ট করুন',
      'found_bug': 'বাগ পেয়েছেন? আমাদের জানান',
      'book_session': 'সেশন বুক করুন',
      'chat': 'চ্যাট',
      'progress': 'অগ্রগতি',
      'wallet': 'ওয়ালেট',
      'dashboard': 'ড্যাশবোর্ড',
      'requests': 'অনুরোধ',
      'earnings': 'আয়',
      'availability': 'উপলব্ধতা',
      'student_menu': 'ছাত্র মেনু',
      'mentor_menu': 'মেন্টর মেনু',
      'help_support': 'সাহায্য ও সহায়তা',
      'websocket_demo': 'ওয়েবসকেট ডেমো',
      'realtime_features_demo': 'রিয়েল-টাইম ফিচার ডেমো',
    },
    'es': {
      'settings': 'Configuración',
      'dark_mode': 'Modo Oscuro',
      'language': 'Idioma',
      'currently': 'Actualmente',
      'sound_effects': 'Efectos de Sonido',
      'vibration': 'Vibración',
      'theme_changed': 'Tema cambiado exitosamente',
      'language_changed': 'Idioma cambiado a',
      'select_language': 'Seleccionar Idioma',
      'cancel': 'Cancelar',
      'notifications': 'Notificaciones',
      'account': 'Cuenta',
      'home': 'Inicio',
      'profile': 'Perfil',
      'logout': 'Cerrar Sesión',
      'privacy_security': 'Privacidad y Seguridad',
      'payment_methods': 'Métodos de Pago',
      'push_notifications': 'Notificaciones Push',
      'email_notifications': 'Notificaciones de Email',
      'study_reminders': 'Recordatorios de Estudio',
      'session_reminders': 'Recordatorios de Sesión',
      'notification_settings': 'Configuración de Notificaciones',
      'app_preferences': 'Preferencias de la App',
      'data_storage': 'Datos y Almacenamiento',
      'learning': 'Aprendizaje',
      'teaching': 'Enseñanza',
      'support': 'Soporte y Legal',
      'password_privacy_settings': 'Contraseña, configuración de privacidad',
      'manage_cards_billing': 'Gestionar tarjetas y facturación',
      'receive_notifications_device':
          'Recibir notificaciones en tu dispositivo',
      'get_updates_email': 'Recibir actualizaciones por email',
      'daily_study_reminders': 'Recordatorios diarios de sesión de estudio',
      'upcoming_session_notifications': 'Notificaciones de sesiones próximas',
      'customize_notification_preferences':
          'Personalizar preferencias de notificación',
      'use_dark_theme': 'Usar tema oscuro',
      'play_sounds_actions': 'Reproducir sonidos para acciones de la app',
      'vibrate_notifications': 'Vibrar para notificaciones',
      'auto_sync': 'Sincronización Automática',
      'automatically_sync_data': 'Sincronizar datos automáticamente',
      'data_usage': 'Uso de Datos',
      'download_content': 'Descargar contenido',
      'clear_cache': 'Limpiar Caché',
      'free_storage_space': 'Liberar espacio de almacenamiento',
      'offline_content': 'Contenido Offline',
      'manage_downloaded_materials': 'Gestionar materiales descargados',
      'session_preferences': 'Preferencias de Sesión',
      'default_session_duration':
          'Duración predeterminada de sesión, descansos',
      'learning_goals': 'Objetivos de Aprendizaje',
      'set_study_targets': 'Establecer tus objetivos de estudio',
      'performance_tracking': 'Seguimiento de Rendimiento',
      'track_progress': 'Cómo seguimos tu progreso',
      'availability_settings': 'Configuración de Disponibilidad',
      'set_teaching_hours': 'Establecer tus horas de enseñanza',
      'rate_preferences': 'Preferencias de Tarifas',
      'hourly_rates_subjects': 'Establecer tarifas por hora por materia',
      'student_management': 'Gestión de Estudiantes',
      'manage_student_interactions': 'Gestionar interacciones con estudiantes',
      'help_center': 'Centro de Ayuda',
      'faq_tutorials': 'FAQ y tutoriales',
      'contact_support': 'Contactar Soporte',
      'get_help_issues': 'Obtener ayuda con problemas',
      'terms_conditions': 'Términos y Condiciones',
      'privacy_policy': 'Política de Privacidad',
      'about_app': 'Acerca de la App',
      'version_info': 'Información de versión y app',
      'check_updates': 'Verificar Actualizaciones',
      'rate_app': 'Calificar App',
      'help_us_improve': 'Ayúdanos a mejorar',
      'report_issue': 'Reportar Problema',
      'found_bug': '¿Encontraste un error? Déjanos saber',
      'book_session': 'Reservar Sesión',
      'chat': 'Chat',
      'progress': 'Progreso',
      'wallet': 'Billetera',
      'dashboard': 'Panel',
      'requests': 'Solicitudes',
      'earnings': 'Ganancias',
      'availability': 'Disponibilidad',
      'student_menu': 'Menú Estudiante',
      'mentor_menu': 'Menú Mentor',
      'help_support': 'Ayuda y Soporte',
      'websocket_demo': 'Demo WebSocket',
      'realtime_features_demo': 'Demo funciones en tiempo real',
    },
    'fr': {
      'settings': 'Paramètres',
      'dark_mode': 'Mode Sombre',
      'language': 'Langue',
      'currently': 'Actuellement',
      'sound_effects': 'Effets Sonores',
      'vibration': 'Vibration',
      'theme_changed': 'Thème changé avec succès',
      'language_changed': 'Langue changée en',
      'select_language': 'Sélectionner la Langue',
      'cancel': 'Annuler',
      'notifications': 'Notifications',
      'account': 'Compte',
      'home': 'Accueil',
      'profile': 'Profil',
      'logout': 'Déconnexion',
      'privacy_security': 'Confidentialité et Sécurité',
      'payment_methods': 'Méthodes de Paiement',
      'push_notifications': 'Notifications Push',
      'email_notifications': 'Notifications Email',
      'study_reminders': 'Rappels d\'Étude',
      'session_reminders': 'Rappels de Session',
      'notification_settings': 'Paramètres de Notification',
      'app_preferences': 'Préférences de l\'App',
      'data_storage': 'Données et Stockage',
      'learning': 'Apprentissage',
      'teaching': 'Enseignement',
      'support': 'Support et Légal',
      'password_privacy_settings':
          'Mot de passe, paramètres de confidentialité',
      'manage_cards_billing': 'Gérer les cartes et la facturation',
      'receive_notifications_device':
          'Recevoir des notifications sur votre appareil',
      'get_updates_email': 'Recevoir des mises à jour par email',
      'daily_study_reminders': 'Rappels quotidiens de session d\'étude',
      'upcoming_session_notifications': 'Notifications de sessions à venir',
      'customize_notification_preferences':
          'Personnaliser les préférences de notification',
      'use_dark_theme': 'Utiliser le thème sombre',
      'play_sounds_actions': 'Jouer des sons pour les actions de l\'app',
      'vibrate_notifications': 'Vibrer pour les notifications',
      'auto_sync': 'Synchronisation Auto',
      'automatically_sync_data': 'Synchroniser automatiquement les données',
      'data_usage': 'Utilisation des Données',
      'download_content': 'Télécharger le contenu',
      'clear_cache': 'Vider le Cache',
      'free_storage_space': 'Libérer l\'espace de stockage',
      'offline_content': 'Contenu Hors-ligne',
      'manage_downloaded_materials': 'Gérer les matériaux téléchargés',
      'session_preferences': 'Préférences de Session',
      'default_session_duration': 'Durée de session par défaut, pauses',
      'learning_goals': 'Objectifs d\'Apprentissage',
      'set_study_targets': 'Définir vos objectifs d\'étude',
      'performance_tracking': 'Suivi des Performances',
      'track_progress': 'Comment nous suivons vos progrès',
      'availability_settings': 'Paramètres de Disponibilité',
      'set_teaching_hours': 'Définir vos heures d\'enseignement',
      'rate_preferences': 'Préférences de Tarifs',
      'hourly_rates_subjects': 'Définir les tarifs horaires par matière',
      'student_management': 'Gestion des Étudiants',
      'manage_student_interactions':
          'Gérer les interactions avec les étudiants',
      'help_center': 'Centre d\'Aide',
      'faq_tutorials': 'FAQ et tutoriels',
      'contact_support': 'Contacter le Support',
      'get_help_issues': 'Obtenir de l\'aide pour les problèmes',
      'terms_conditions': 'Conditions d\'Utilisation',
      'privacy_policy': 'Politique de Confidentialité',
      'about_app': 'À Propos de l\'App',
      'version_info': 'Informations de version et d\'app',
      'check_updates': 'Vérifier les Mises à Jour',
      'rate_app': 'Évaluer l\'App',
      'help_us_improve': 'Aidez-nous à nous améliorer',
      'report_issue': 'Signaler un Problème',
      'found_bug': 'Bug trouvé? Faites-le nous savoir',
      'book_session': 'Réserver Session',
      'chat': 'Discussion',
      'progress': 'Progrès',
      'wallet': 'Portefeuille',
      'dashboard': 'Tableau de Bord',
      'requests': 'Demandes',
      'earnings': 'Gains',
      'availability': 'Disponibilité',
      'student_menu': 'Menu Étudiant',
      'mentor_menu': 'Menu Mentor',
      'help_support': 'Aide et Support',
      'websocket_demo': 'Démo WebSocket',
      'realtime_features_demo': 'Démo fonctionnalités temps réel',
    },
  };

  static String translate(String key, Locale locale) {
    final languageCode = locale.languageCode;
    return _translations[languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }

  // Custom LocalizationsDelegate
  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations._();
  }

  const AppLocalizations._();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any((supportedLocale) =>
        supportedLocale.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return const AppLocalizations._();
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
